name: 'nhl_analytics'
version: '1.0.0'
config-version: 2

profile: 'nhl'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  nhl_analytics:
    # Bronze layer: Raw data views - immutable source of truth
    bronze:
      +materialized: view
      +schema: bronze
      +tags: ['bronze', 'raw']
    
    # Silver layer: Cleaned, conformed data - single source of truth
    silver:
      +materialized: table
      +schema: silver
      +tags: ['silver']
    
    # Staging models (views over raw tables) - legacy
    staging:
      +materialized: view
      +schema: staging
