# ============================================================================
# LEGACY WORKFLOW - DISABLED
# ============================================================================
# This workflow is preserved for reference but is NOT executed by GitHub Actions.
# Workflows must be in .github/workflows/ to run; this is in workflows-legacy/.
#
# Purpose: Snowflake Time Travel data quality validation
# Disabled: 2026-02 - Project migrated from Snowflake to Apache Iceberg
# Replacement: TBD - Iceberg-native validation approach
# ============================================================================

name: Data Quality Validation

on:
  # Run after dbt transformations complete
  workflow_run:
    workflows: ["Deploy to MWAA"]
    types:
      - completed
  
  # Or run on schedule (every 4 hours)
  schedule:
    - cron: '0 */4 * * *'
  
  # Allow manual trigger
  workflow_dispatch:
    inputs:
      lookback_minutes:
        description: 'Minutes to look back for comparison'
        required: false
        default: '60'

jobs:
  validate:
    runs-on: ubuntu-latest
    # Only run if the workflow_run triggered this AND it was successful
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name != 'workflow_run' }}
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Setup Snowflake private key
        run: |
          mkdir -p ~/.snowflake
          echo "${{ secrets.SNOWFLAKE_PRIVATE_KEY }}" > ~/.snowflake/rsa_key.p8
          chmod 600 ~/.snowflake/rsa_key.p8
      
      - name: Run Time Travel validation
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PRIVATE_KEY_PATH: ~/.snowflake/rsa_key.p8
          SNOWFLAKE_WAREHOUSE: NHL_WH
          SNOWFLAKE_DATABASE: NHL
          SNOWFLAKE_ROLE: TRANSFORMER
          LOOKBACK_MINUTES: ${{ github.event.inputs.lookback_minutes || '60' }}
        run: |
          make validate-data
      
      - name: Notify on failure
        if: ${{ failure() && env.SLACK_WEBHOOK_URL != '' }}
        uses: slackapi/slack-github-action@v1
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          payload: |
            {
              "text": "⚠️ Data Quality Validation Failed",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Data Quality Alert*\nTime Travel validation detected unexpected changes in data.\n\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Run>"
                  }
                }
              ]
            }
